lsst-sqre/safir

docs/set-up-from-template.rst

roundtable_aiohttp_bot is now merged to the master branch of
templates, so there's no need to clone a specific ticket branch
(and that branch no longer exists).

Adjust documentation for templates PR merge

---

docs/logging.rst

The logger is stored on the request directly as a key, not on the
config_dict as a key.

[DM-23923] Fix logging docs

---

.github/dependabot.yml

Enable GitHub Actions and PIP dependency monitoring.  This will
also switch to using the GitHub integrated Dependabot instead of
Dependabot Preview, allowing us to eventually remove the latter
application.

[DM-25844] Add configuration for Dependabot

---

.github/workflows/ci.yaml
.pre-commit-config.yaml
CHANGELOG.rst
docs/logging.rst
docs/storage-keys.rst
pyproject.toml
setup.cfg
src/safir/__init__.py
src/safir/logging.py
src/safir/metadata.py
src/safir/middleware.py
tests/logging_test.py
tests/metadata_test.py
tests/middleware_test.py

Update dev and pre-commit dependencies and apply corresponding
changes.
Each time safir was configured, it stacked another handler into
the safir logger.  This meant that if logging was repeatedly
configured in the same Python process, all log output to stdout
would be duplicated.  This primarily affected test suites, where
each test would reinitialize logging.  The impact was that failed
tests from files with lots of tests would have log out duplicated
a number of times equal to the number of tests, which made it hard
to find the error or understand the output.
Avoid this by clearing the handlers in the safir logger each time
logging is configured to ensure that only the single, wanted handler
is added.

[DM-28114] Update dev dependencies, fix duplicate logging

---

CHANGELOG.rst
setup.cfg
src/safir/logging.py
tests/logging_test.py

Kubernetes tracks the timestamp of each output line internally, so
this is not strictly necessary for our Kubernetes services, but
Argo CD doesn't display that timestamp and other log aggregation may
not necessarily.  Add an optional argument to configure_logging to
allow an application to request a timestamp be added to each log
message.

[DM-30689] Optionally add a timestamp to log messages

---

CHANGELOG.rst
src/safir/dependencies/http_client.py

The approach of creating one AsyncClient on startup and destroying
that one client without a way of recreating it on shutdown works
fine for the application when run normally, but fails in test
scenarios that reuse the application.
Instead, defer creation of the AsyncClient until the first time
it's requested, clear it on aclose(), and recreate it if it's asked
for again.  This allows applications to aclose() the client on
shutdown but still work when the same app object is reused for
multiple tests.

[DM-28130] Delay AsyncClient creation and allow recreation

---

CHANGELOG.rst
docs/api.rst
src/safir/dependencies/http_client.py
src/safir/dependencies/logger.py
src/safir/models.py
tests/models_test.py

- Add the `ErrorModel` to Safir (useful for documentation)
- Mark all dependencies as async so that they won't be run in a thread pool

[DM-31361] Safir improvements from mobu

---

.github/workflows/ci.yaml

Don't try to upload documentation on pull requests unless the
pull request is from a ticket branch.  This avoids failed
documentation uploads from dependabot PRs.
Update the CI workflow to match the current recommendation, so that
the workflow is run on pull requests, pre-commit is run with its
own action, and we cache the tox environments.

[DM-31621] Update GitHub Actions workflow

---

CHANGELOG.rst
setup.cfg
src/safir/logging.py
tests/logging_test.py

Per the release notes of structlog 21.2.0:
* To implement pretty exceptions (see Changes below),
structlog.dev.ConsoleRenderer now formats exceptions itself.
Make sure to remove format_exc_info from your processor chain if
you configure structlog manually.
Do this.  Also adapt the test suite to handle color logging for
the dev logger (which is now enabled by default) and explicitly
check exception handling for both loggers.

Update for structlog 21.2.0

---

.pre-commit-config.yaml
CHANGELOG.rst
setup.cfg
src/safir/dependencies/http_client.py
tests/dependencies/http_client_test.py

- Enable redirects by default, restoring the previous behavior
- Depend on the version of httpx adding the new redirect behavior
- Switch from pytest-httpx to respx for testing
- Install `py.typed` so that mypy knows to use type annotations in this library
- Update pre-commit hooks

[DM-32520] Adjust for new httpx

---

CHANGELOG.rst
src/safir/testing/kubernetes.py

Update patch_namespaced_custom_object_status to expect a JSON
patch rather than a merge patch, enabling a workaround for a bug
in kubernetes-asyncio.

[DM-33121] Change expected patch body for custom objects

---

CHANGELOG.rst
src/safir/testing/kubernetes.py

Not a full implementation of the API.  Currently, it requires a
field_selector be given to restrict the result to a single pod,
since that's what's required for testing moneypenny.
Stop inheriting from `Mock`, since it causes weird errors and
doesn't appear to be doing anything useful for us.

[DM-33244] Add basic support for list_namespaced_pod testing

---

CHANGELOG.rst
docs/x-forwarded.rst
src/safir/dependencies/logger.py
src/safir/middleware/x_forwarded.py
tests/dependencies/logger_test.py
tests/middleware/x_forwarded_test.py

In the XForwardedMiddleware, rather than storing the forwarded
scheme from X-Forwarded-Proto in the request state, simply update
the scope of the request so that Starlette will think the incoming
scheme was the sheme from X-Forwarded-Proto.  Drop the state
variable that was previously set.
This will ensure that other Starlette functions such as url_for
will pick up the correct scheme and thus generate URLs that
correctly use https even if the service is behind an ingress that
terminates TLS.

[DM-33604] Improve handling of X-Forwarded-Proto

---

CHANGELOG.rst
docs/api.rst
docs/conf.py
docs/gafaelfawr.rst
docs/index.rst
docs/logging.rst
src/safir/dependencies/gafaelfawr.py
tests/dependencies/gafaelfawr_test.py

Add new auth_dependency and auth_logger_dependency FastAPI
dependencies for applications protected by Gafaelfawr.  The former
returns the authenticated user from the header set by Gafaelfawr,
and the latter wraps logger_dependency and adds the authenticated
user as a bound context variable.

[DM-33604] Add FastAPI dependencies for Gafaelfawr auth

---

pyproject.toml
tox.ini

Unfortunately, tox-docker (which will be used shortly for
testing database code) doesn't support putting the tox
configuration into pyproject.yaml.  We've also switched to a
separate tox.ini in our standard project template, so may as well
make Safir match.

[DM-33604] Move tox configuration to tox.ini

---

Makefile

Add the --upgrade flag to upgrade to the latest versions of
dependencies, and explicitly upgrade pip.  This more closely
follows the practices of other Python packages we maintain.

[DM-33604] Upgrade dependencies during make init

---

docs/conf.py
docs/database.rst
src/safir/database.py
src/safir/dependencies/gafaelfawr.py
src/safir/dependencies/logger.py
src/safir/logging.py
src/safir/metadata.py
src/safir/middleware/x_forwarded.py
tox.ini

Add a nitpick_ignore configuration for all the types seen in type
signatures that do not provide intersphinx, and disable automatic
inheritence of members from parent classes to avoid tons of noise
from Pydantic.  Use the cleaner warning list to fix various typos,
incorrect references, and other API documentation bugs.  Remove the
if TYPE_CHECKING conditional in a few files so that Sphinx can
properly resolve the references.
Make documentation warnings fatal so that we can maintain the
clean build going forward.

[DM-33604] Fix all documentation warnings

---

docs/database.rst

Add a documentation section on how to test applications that use
databases, including tox-docker configuration and fixtures.
Move some of the less-used database utility functions into an
"Less-used database operations" section.

[DM-33604] Document testing applications that use databases

---

CHANGELOG.rst
docs/database.rst
src/safir/database.py
src/safir/dependencies/db_session.py
tests/database_test.py
tests/dependencies/db_session_test.py

After testing with the applications that use this database support, some parts of the API were clunky or didn't allow enough connection sharing to try to optimize test suite execution times. FastAPI 0.74 also introduced a new problem that made the managed transactions mode fail. Make the following changes:
- Change `iniitalize_database` to take the engine as a parameter, rather than create a new engine that the caller is responsible for freeing. The caller should call `create_database_engine` first instead, and let it handle authentication.
- Allow overriding the engine used by `db_session_dependency` in case an application wants to share a connection pool among tests.
- Remove managed transactions mode for `db_session_dependency` since it doesn't work with FastAPI 0.74 and later with …

[DM-33662] Refinements to the database support

---

CHANGELOG.rst
docs/database.rst
src/safir/database.py
tests/database_test.py

This allows non-standard Postgres port settings to be respected. I sometimes use a different port for either the "dev" or "test" containers to avoid conflicts when running tests while also running a dev instance of the app locally.
Also fixes a typo in the "init" CLI function example.

DM-33627: Retain port setting in safir.database

---

.github/workflows/ci.yaml
.github/workflows/periodic.yaml
setup.cfg

Unpin development dependencies to avoid dependabot needing to send
PRs for dependency updates every week.
Check compatibility with the latest released versions by running a
separate CI job weekly that does not cache the tox environments and
thus will use the latest versions of all dependencies.
Enable the normally-not-used setup-python caching so that we can share
a pip cache between the regular CI job and the periodic job.
Bump the version used for documentation and PyPI workflows to the latest
Python release.

[DM-33981] Unpin dependencies, test weekly

---

CHANGELOG.rst
src/safir/database.py
tests/database_test.py
tox.ini

Be more careful about URL quoting when rewriting database URLs in
safir.database so that passwords containing characters with special
meaning in URLs (@, /) are handled correctly.
urlparse doesn't undo quoting, so use a test database password
containing various special characters for a thorough test.

[DM-34097] Fix database passwords with special characters

---

src/safir/metadata.py
tests/metadata_test.py

In the latest mypy (0.942), importlib.metadata.metadata now returns
a Protocol named PackageMetadata that doesn't implement the get
method.  The actual object remains a Message class, however, so the
get method works correctly.  Only mypy checking fails.
Pending https://github.com/python/typeshed/issues/7767 which may
reveal that it is intentional that get not be supported, cast the
return value to Message so that the existing functions work.  This
seems better than adding try/catch blocks for every piece of
metadata of interest given that the omission of get appears to be
unintentional.

Add casts for package metadata

---

CHANGELOG.rst
src/safir/dependencies/logger.py
src/safir/middleware/x_forwarded.py
tests/middleware/x_forwarded_test.py

The latest version of FastAPI and Starlette allows request.client
to not be set at all, instead of merely set to a tuple of None.
This required some updates to Safir's code that were caught by
mypy.

[DM-34821] Allow request.client to be None

---

CHANGELOG.rst
docs/api.rst
docs/index.rst
docs/ivoa.rst
src/safir/middleware/ivoa.py
tests/middleware/ivoa_test.py
tox.ini

This now has two users: vo-cutouts and datalinker.  Share the code
via Safir, particularly since we expect to write more IVOA protocol
implementations in the future.
Add the documentation build to the tox envlist so that it's run as part
of `tox -p all`. This helps with catching documentation warnings before
CI fails.

[DM-35033] Add CaseInsensitiveQueryMiddleware

---

setup.cfg

Sphinx 5.1.0 has an incompatibility with the napoleon extension
that causes the documentation build to break with the error:
"IndexError: pop from an empty deque".
Per https://github.com/sphinx-doc/sphinx/issues/10701 avoid the
5.1.0 version in the hope that the next release will fix this.

Avoid Sphinx 5.1.0

---

CHANGELOG.rst
src/safir/metadata.py

Update safir.metadata.get_metadata to first try the new package
metadata naming conventions and fields for pyproject.toml-only
packages, and fall back on the older names.

[DM-28121] Handle the new pyproject.toml package metadata

---

src/safir/database.py
src/safir/dependencies/db_session.py

Mypy not longer accepts `sqlalchemy.engine.create._IsolationLevel` as a valid type:
```
src/safir/database.py:131: error: Variable "sqlalchemy.engine.create._IsolationLevel" is not valid as a type src/safir/database.py:131: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
```
This PR simply removes the use of `_IsolationLevel` for type checking and uses the str type throughout instead. I don't know if there's a more sophisticated solution, but this at least unblocks a clean CI.

DM-36156: Drop use of sqlalchemy _IsolationLevel type

---

CHANGELOG.md
docs/user-guide/logging.rst
src/safir/logging.py

Add a new function, configure_uvicorn_logging, which overrides the Uvicorn logging configuration to use structlog and adds processors to add the log severity and (for access logs) the details of the request as structlog context.  The context is formatted so that, if logged as JSON, the fields match the expectation of Google's Cloud Logging system.
Unfortunately, there doesn't appear to be an easy way to test this function inside Safir's test suite, since Uvicorn is not friendly to being run as a fixture or in the course of a test function.

[DM-35879] Support sending Uvicorn logs through structlog

---

.github/workflows/periodic.yaml

Graphviz is needed for API docs, so this will resolve the periodic CI failure.

Install graphviz for periodic doc build

---

CHANGELOG.md
src/safir/logging.py
tests/logging_test.py

Add enums with the acceptable values of Profile and LogLevel for configure_logging and configure_uvicorn_logging.  Modify those functions to accept either strings or enums, for backward compatibility.
This change is in preparation for converting the FastAPI template to use pydantic.BaseSettings instead of a dataclass for its Configuration class.  These enums will be used to validate the profile and log_level settings.
This also changes the name of the argument to configure_uvicorn_logging for consistency with configure_logging. Technically this is a backwards-incompatible change, but the recommended way of calling this function doesn't use a named argument, so hopefully this won't break anything.

DM-37046: Add Profile and LogLevel enums

---

src/safir/arq.py
src/safir/asyncio.py
src/safir/database.py
src/safir/dependencies/arq.py
src/safir/dependencies/db_session.py
src/safir/dependencies/logger.py
src/safir/logging.py
src/safir/metadata.py
src/safir/middleware/x_forwarded.py
src/safir/testing/kubernetes.py

The current documenteer setup correctly resolves types and doesn't require reiterating them in docstrings in most cases.  Drop them where possible.  Add better docstrings to datetime_from_db and datetime_to_db.
For reasons that I don't understand, structlog.types.EventDict doesn't resolve unquoted but does work in backticks, so add backticks to keep Sphinx happy.

DM-37051: Drop now-unnecessary types from docs

---

docs/api.rst

This adds safir.asyncio to the API reference.

Generate API docs for safir.asyncio

---

CHANGELOG.md
docs/user-guide/pydantic.rst
src/safir/pydantic.py
tests/pydantic_test.py

Add new helper class safir.pydantic.CamelCaseModel, which is identical to pydantic.BaseModel except with configuration added to accept camel-case keys using the safir.pydantic.to_camel_case alias generator.  This is a bit less self-documenting, but is less tedious if there are a lot of classes that need this configuration (such as a complex Kubernetes custom object model).

DM-37291: Add CamelCaseModel helper class

---

CHANGELOG.md
Makefile
docs/api.rst
docs/documenteer.toml
docs/user-guide/arq.rst
docs/user-guide/gcs.rst
docs/user-guide/index.rst
pyproject.toml
src/safir/gcs.py
src/safir/testing/gcs.py
tests/conftest.py
tests/gcs_test.py
tests/testing/conftest.py
tests/testing/gcs_test.py
tox.ini

crawlspace, datalinker, and vo-cutouts all use Google Cloud Storage and have some overlapping needs. Lift the relevant code into Safir. This adds:
- A `safir.gcs.SignedURLService` class that uses workload identity credentials to obtain signing credentials and sign URLs. This is somewhat inefficient as written, but having it in Safir will allow us to improve it later, to everyone's benefit. This is currently only used by vo-cutouts, but should eventually be used by datalinker once we do the work of teaching Butler to use workload identity.
- A `safir.testing.gcs.patch_google_storage` function and associated mock classes to mock out Google Cloud Storage during tests. This supports two versions of mocked blobs, once that only supports synthetic signed URLs and one that mocks more of the …

DM-37516: Add Google Cloud Storage utilities and testing support

---

CHANGELOG.md
docs/user-guide/fastapi-errors.rst
docs/user-guide/index.rst
src/safir/models.py

Add an enum representing the valid first members of the loc array in the ErrorDetail model.  Due to the array (and backward compatibility) the typing can't be enforced, but it's still of use to applications that use Safir and construct custom errors.

DM-37589: Add ErrorLocation enum to models

---

CHANGELOG.md
docs/api.rst
docs/user-guide/database.rst
docs/user-guide/datetime.rst
docs/user-guide/index.rst
docs/user-guide/pydantic.rst
src/safir/datetime.py
src/safir/pydantic.py
tests/datetime_test.py
tests/pydantic_test.py

These are fairly small, but I find myself copying and pasting them between projects anyway.  current_datetime provides a normalized datetime for the current time.  isodatetime and parse_isodatetime handle the most useful version of ISO 8601 date representation. normalize_isodatetime does the same for input to Pydantic models in cases where accepting all the variations that Pydantic accepts isn't desirable.

DM-37589: Add datetime utility functions

---

src/safir/pydantic.py

The example was still referring to normalize_datetime.

DM-37589: Fix example for normalize_isodatetime

---

CHANGELOG.md
docs/_rst_epilog.rst
docs/dev/development.rst
docs/dev/release.rst

Adopt the change log format used by Gafaelfawr, which divides change log entries into four standard sections. Document the new format and change the existing entries to match.
Change some references from `master` to `main`.

DM-37760: Change the change log format

---

src/safir/database.py

SQLAlchemy has support for Postgres-like schemas (in the Posgtres-esque "namespace-of-tables" sense of "schema", not the general "collection of table definitions" sense) and this can be quite useful e.g. as a way of partitioning off dedicated versions of tables for testing so test targets can be executed against a running db server without interfering/colliding with non-test data which may be already loaded there.
It is already reasonably straightforward for a Safir user to set this up in a config-driven way in their SQLAlchemy `Base` ORM declaration:
```Python
from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase
from ..config import config
class Base(DeclarativeBase):
metadata = MetaData(schema=config.database_schema)
```
...where `database_schema` is a `str | None` …

Add support for initialization of non-default schema 

---

pyproject.toml

The Google cloud Python packages use pkg_resources, and therefore spew warnings when imported. We can't do anything about those and presumably they'll eventually be fixed upstream, so suppress them.

DM-38466: Suppress pkg_resources warnings

---

.github/workflows/periodic.yaml

When updating the minimum Python versions elsewhere, I missed the periodic CI job.

DM-38466: Update Python versions in periodic CI

---

docs/user-guide/database.rst

Fritz added initialize_database support for non-default PostgreSQL schemas in 3.7.0. The details he included in his pull request seem worth mentioning in the documentation, since configuring this is simple but not obvious.

DM-38466: Document using non-default PostgreSQL schemas

---

CHANGELOG.md
src/safir/dependencies/gafaelfawr.py

auth_dependency and auth_logger_dependency pull the username from the X-Auth-Request-User header, set by Gafaelfawr. By default, any header parameters like this are also added to the OpenAPI schema of routes that use them. However, in this case that addition is incorrect; X-Auth-Request-User is an internal implementation detail of Gafaelfawr-protected applications, not a header that the user can or should supply. Suppress it from the schema accordingly.

DM-38533: Exclude X-Auth-Request-User from the schema

---

CHANGELOG.md
docs/user-guide/kubernetes.rst
src/safir/testing/kubernetes.py
tests/conftest.py
tests/kubernetes_test.py
tests/testing/conftest.py
tests/testing/kubernetes_test.py

In order to test the new Nublado lab controller, we had to make multiple improvements to the Kubernetes mock and fix a few places where it was incompatible with the kubernetes_asyncio API. Merge those changes back into the Safir version and add additional documentation.
This also adds a new strip_none utility function for removing None key values from possibly-nested complex data structures, which makes it easier to compare Kubernetes objects in serialized form.
Add basic API documentation to all the supported methods of the Kubernetes mock. For reasons that I don't understand, this requires fully-qualified types to avoid Sphinx warnings, even though unqualified types have been working everywhere else.

DM-38533: Merge Kubernetes API mock with lab controller work

---

CHANGELOG.md
docs/user-guide/pydantic.rst
src/safir/pydantic.py
tests/pydantic_test.py

Given what it does, this should have always been a root validator. Making it an individual field validator requires being too clever, and requires a very careful calling convention. Convert it to a root validator while we're making backward-incompatible changes.
Make the test suite use a real Pydantic model, which is a better test of how the validator works than calling it directly.

DM-38660: Change validate_exactly_one_of to a root validator

---

CHANGELOG.md
docs/_rst_epilog.rst
docs/api.rst
docs/user-guide/http-client.rst
docs/user-guide/slack-webhook.rst
docs/user-guide/uvicorn.rst
src/safir/dependencies/http_client.py
src/safir/slack/blockkit.py
src/safir/testing/uvicorn.py
tests/middleware/x_forwarded_test.py
tests/slack/blockkit_test.py
tests/slack/webhook_test.py

Provide a SlackWebException base exception class, derived from SlackException, which understands how to extract useful information from HTTPX exceptions so that it can be reported to Slack. It also improves the stringification of HTTPX exceptions, which normally may not include the failing URL in the exception stringification.
Unfortunately, automodapi doesn't generate documentation for class or instance methods of exceptions, so the references to from_exception in the docs can't be links to the documentation.

DM-38660: Add SlackWebException for HTTPX errors

---

src/safir/slack/blockkit.py

The serialization of SlackWebException for Slack reporting didn't take into account the addition of a __str__ method that added the body of the response. That should be omitted from the initial part of the Slack message since it's included in a later block. Adjust the serialization accordingly.

DM-38660: Don't include body twice in SlackWebException

---

CHANGELOG.md
docs/dev/development.rst
docs/user-guide/set-up-from-template.rst

tox v4 added subcommands as the preferred command-line syntax. Executing it without subcommands invokes a default subcommand called "legacy" and the upgrading documentation recommends always using subcommands for tox run and when there may be a conflict with an environment name. Update the documentation to always use the new syntax.

DM-38414: Use new tox v4 syntax

---

CHANGELOG.md
src/safir/testing/kubernetes.py

Add read_namespaced_config_map and read_namespaced_resource_quota to MockKubernetesApi, needed for testing the next version of the Nublado lab controller.

DM-38795: Add read for ConfigMap and ResourceQuota to mock

---

CHANGELOG.md
src/safir/testing/kubernetes.py

The Kubernetes mock was never clearing the `asyncio.Event` used to signal that new namespace events were available, so it was essentially busy-waiting, which in turn starved other tasks and caused very confusing bugs. Adopt the same strategy as Nublado and use separate events per consumer so that they can be triggered separately.
Also switch from `asyncio.wait_for` to `asyncio.timeout`. This turned out to be unrelated to the problem, but some research showed that `asyncio.timeout` is much simpler and has fewer edge-case bugs.

DM-38795: Fix concurrency for event watches

---

CHANGELOG.md
src/safir/testing/kubernetes.py
tests/testing/kubernetes_test.py

Move the machinery for event watches in the Kubernetes mock into a separate private class.
Make use of that machinery to add watch support for list_namespaced_pod. Add patch_namespaced_pod_status to change the phase, primarily for tests (application code is unlikely to call this since pod phase is handled by Kubernetes itself).
If the resource version is not specified to a watch, the watch now starts with the next event, not the first recorded event, to match the behavior of the Kubernetes API.

DM-38795: Add watch support for list_namespaced_pod

---

CHANGELOG.md
src/safir/slack/blockkit.py

Previously, SlackWebException assumed that if an httpx exception inherited from RequestError, it would have a request attribute, and if it didn't, it wouldn't. This turns out to be incorrect; some RequestError exceptions may not have a request for various reasons, and some that do not inherit from RequestError do.
Adjust the exception parsing to take this into account by attempting to extract the request and falling back on the non-request handling on any error.
Fix one place where SlackTextField was used instead of SlackTextBlock for something added to the message blocks. (The different length restriction is unlikely to matter in practice, but this is more correct.)

DM-38425: Extract more data from httpx exceptions

---

CHANGELOG.md
src/safir/testing/kubernetes.py

Add create_namespaced_persistent_volume_claim to the Kubernetes mock.

DM-39232: Add support for creating PVCs to Kubernetes mock

---

CHANGELOG.md

4.2.0 and 4.2.1 were released with an incomplete change log and without finalizing the change log. Flesh it out retroactively.

DM-38933: Add missing change log entries for 4.2.0 and 4.2.1

---

CHANGELOG.md
changelog.d/20230517_100025_rra_DM_39251.md
changelog.d/_template.md
docs/_rst_epilog.rst
docs/dev/development.rst
docs/dev/release.rst
pyproject.toml

scriv maintains change logs in individual fragments that can be merged with the corresponding PR without creating merge conflicts, and then assembles those fragments into a new change log entry during the release process. Move the pending changes to a scriv fragment, add a scriv configuration, and update the development and release documentation to document use of scriv.
Also note in the preamble of the change log that Safir follows semver.

DM-39251: Switch to scriv for change log management

---

changelog.d/20230517_140715_rra_DM_38933.md
src/safir/testing/kubernetes.py

The references to methods in the MockKubernetesApi docstring were intended to be cross-references, and the docs-linkcheck failure seems to go away once the docs target is run first. Revert the documentation change in 4.2.1 in the hope that this was a false positive.

DM-38933: Revert MockKuberntesApi doc change in 4.2.1

---

CHANGELOG.md
docs/_rst_epilog.rst
docs/user-guide/github-apps/create-a-github-client.rst
docs/user-guide/github-apps/webhook-models.rst
src/safir/github/webhooks.py
src/safir/logging.py

Go through docs-linkcheck and convert permanent redirects to their targets, with the exception of a small handful that don't have a stable canonical link.

DM-38933: Fix redirects in documentation

---

changelog.d/20230517_171212_rra_DM_39249.md
src/safir/testing/kubernetes.py
tests/testing/kubernetes_test.py

Add support for the keyword parameter grace_period_seconds and a body of V1DeleteOptions for all delete_* methods in the Kubernetes API mock.
Stop requiring propagation_policy be set for delete_namespaced_job, and require it be given as a keyword parameter.

DM-39249: Support standard Kubernetes delete options

---

changelog.d/20230518_074803_rra_DM_39249a.md
src/safir/slack/blockkit.py

The response portion of a SlackWebException may be a full HTML page, so put it in an attachment rather than a block when formatting it for Slack so that Slack will hide long content by default and add an expand option.

DM-39249: Put response from SlackWebException in attachment

---

docs/user-guide/github-apps/handling-webhooks.rst

The example for setting up a GitHub webhook endpoint was missing the line where the `body` is obtained from the `request` object.

Fix GitHub webhook example for body

---

docs/user-guide/github-apps/create-a-github-client.rst

The documentation used different parameter names for the GitHubAppClientFactory constructor than the code. Make the documentation match the code.

DM-39627: Fix GithHubAppClientFactory parameter names in docs

---

.github/workflows/ci.yaml
.github/workflows/periodic-ci.yaml

Upgrade to v2 of lsst-sqre/build-and-publish-to-pypi and use a trusted environment for upload instead of an organization secret. Add a separate test-packaging target that always runs. Trigger PyPI upload on GitHub release rather than a tag.
Add workflow triggers to make it easier to manually test workflows.
Rename periodic.yaml to periodic-ci.yaml to match the template, and add alerts to Slack if the periodic CI runs fail.

Update GitHub Actions configuration

---

Makefile
tox.ini

Sphinx doesn't summarize the linkcheck errors at the end of the output, but it does write them to output.txt. Move the link checking to a makefile target so that we can use shell trickery to output the contents of that file on link checking failures.
Add help and clean targets to the Makefile, and remove docs/api when building docs to avoid stale files left-over from automodsumm.

DM-40495: Improve error reporting from docs-linkcheck

---

changelog.d/20230830_155927_rra_DM_40567.md
docs/api.rst
docs/documenteer.toml
docs/user-guide/click.rst
docs/user-guide/index.rst
pyproject.toml
src/safir/click.py
tests/click_test.py

For the Phalanx command-line tool, I added support for a second level of commands to the standard help boilerplate. The result is complex enough that it seems worth lifting into Safir proper rather than existing only in a template. The result is a new safir.click module providing a display_help function.
Add documentation of the run_with_asyncio decorator to the new user guide page about Click support, since this is the most common place where that decorator is used.

DM-40567: Add a helper function for Click command help

---

changelog.d/20230905_090034_rra_DM_40638.md
docs/api.rst
docs/user-guide/asyncio-queue.rst
docs/user-guide/index.rst
src/safir/asyncio.py
src/safir/testing/kubernetes.py
tests/asyncio_test.py

Add an asyncio multiple writer, multiple reader queue, and convert the Kubernetes mock to use it instead of implementing its own. This data structure is also used in the JupyterHub REST spawner and in the Nublado lab controller.

DM-40638: Add AsyncMultiQueue data structure

---

changelog.d/20230905_090226_rra_DM_40638a.md
src/safir/asyncio.py

Use the new ParamSpec support to correctly type the run_with_asyncio decorator, allowing type-checking of the call to its decorated function.

DM-40638: Improve typing of run_with_asyncio

---

changelog.d/20230907_110606_rra_DM_40638b.md
docs/_rst_epilog.rst
docs/user-guide/kubernetes.rst
src/safir/testing/kubernetes.py
tests/testing/kubernetes_test.py

In the Kubernetes mock, objects serialized into watch events were not being serialized properly. They were keeping the Python snake-case attribute names instead of the Kubernetes camel-case names. This prevented deserialization to Kubernetes model objects and was also confusing.
Fix this by passing the serialize parameter to to_dict when serializing the objects, and restructure the code a bit to reduce duplicate work. Add an explicit test for proper object serialization and deserialization.
When mocking the Kubernetes API, stop mocking the entire ApiClient, since we need to use its deserialize method to convert watch events to their proper types. Due to the other mocking, we should never make network calls, but mock the request method of ApiClient just in case.

DM-40638: Fix serialization of objects in watch events

---

changelog.d/20230907_135241_rra_DM_40638b.md
src/safir/testing/kubernetes.py

Add read methods for the Kubernetes object types for which the mock provided create methods. This is required by the new generic Kubernetes storage layer in the Nublado lab controller.

DM-40638: Add mock Kubernetes read methods for more kinds

---

changelog.d/20230908_143247_rra_DM_40691.md
src/safir/testing/kubernetes.py

Add support for list_namespaced_custom_object, including watch support, to the Kubernetes mock. Update the resource version field of custom objects appropriately.

DM-40691: Add list_namespaced_custom_object to mock

---

changelog.d/20230908_150940_rra_DM_40691.md
src/safir/testing/kubernetes.py

Ingress, Job, and Service objects previously didn't correctly maintain resource versions on all object updates, but they support watches which in turn rely on resource versions. Add the necessary resource version updates.

DM-40691: Maintain more resource versions in Kubernetes mock

---

changelog.d/20230908_152325_rra_DM_40691_queue.md
src/safir/testing/kubernetes.py

Randomize the Pod name in a similar way that Kubernetes does when the default generateName behavior is used. If an explicit name was set in the pod template in the Job, use that name; don't replace it with a generated name. Honor generateName set in the pod template in the Job.

DM-40691: Make Pod creation from a Job more correct in mock

---

changelog.d/20230912_145508_rra_DM_40691.md
src/safir/testing/kubernetes.py

Add watch, field selector, and label selector support to list_namespace in the Kubernetes mock.
read_namespace and list_namespace in the Kubernetes mock now only return namespace objects that have been explicitly created, not implicit namespaces created by creating another object without making a namespace first. This more closely matches the behavior of Kubernetes while still making it easy to use the mock in a test environment simulating a pre-existing namespace.
Fix the documentation for label_selector in list_* functions to reflect that it is applied to the regular list return, not just the watch.

DM-40691: Add watch support for namespaces

---

changelog.d/20230914_173515_jsick_DM_39710_remove_app_factory.md
docs/user-guide/github-apps/create-a-github-client.rst
src/safir/github/_client.py

This method was mistakenly added with sufficient testing and never worked. The Gidgethub API cannot cache an app JWT with its current API. The documentation now features the correct workflow, which requires manually obtaining the JWT and passing it with each release.
Since this is technically a breaking change, it should be included with the next major release. However, since the API was never usable, there shouldn't be any issue removing it.

DM-398710: Remove GitHubAppClientFactory.create_app_client

---

docs/user-guide/uvicorn.rst

There was a remaining bug in one of the examples where the fixture was yielding a non-existent variable, and the name of the fixture conflicted with the name of a local variable. Fix both of those, and add a try/finally block to make sure that the process is always shut down on any errors.

Fix spawn_uvicorn documentation

---

changelog.d/20231003_135049_rra_DM_23878.md
src/safir/logging.py
tests/logging_test.py

When configuring a FastAPI application with debug logging, I used "debug" instead of "DEBUG" in the configuration and was then annoyed that the server didn't start with an error. The function call supported a string with any case, but the Pydantic model we use to validate most configurations required uppercase because it relied on the enum to do the validation.
Implement a `_missing_` method for the LogLevel enum that converts strings in any case to the expected uppercase, which allows Pydantic validation of models to work with any case of the log level and still validates and returns the correct log level.

DM-23878: Allow log level enum with any case

---

changelog.d/20231110_124506_rra_DM_41630.md
src/safir/testing/kubernetes.py

Add a validated but ignored optional propagation_policy argument to every Kubernetes mock delete method to more closely match the actual Kubernetes API. This argument was previously only supported for delete_namespaced_job. It has no effect on the behavior of the other mock methods.

DM-41630: Add propagation_policy to Kubernetes mock deletes

---

changelog.d/20231110_141912_rra_DM_41630.md
src/safir/testing/kubernetes.py

Accept and ignore the _request_timeout parameter in all Kubernetes mock methods.

DM-41630: Support _request_timeout in Kubernetes mock

---

changelog.d/20231110_165902_rra_DM_41630b.md
src/safir/testing/kubernetes.py

This parameter is actually a float, not an int. This largely doesn't matter since the types of the mock are ignored and kubernetes_asyncio is currently untyped, but be more correct anyway.

DM-41630: Fix type of Kubernetes mock _request_timeout

---

pyproject.toml
tests/conftest.py

redis-py 5.0.0 changed the async close method from close to aclose, and types-redis is no longer accurate for the library. Drop the types-redis development dependency, add a versioned development dependency, and use aclose instead of close to avoid a warning when running the test suite.

DM-41630: Update development Redis dependencies

---

docs/user-guide/arq.rst
docs/user-guide/database.rst
docs/user-guide/http-client.rst
docs/user-guide/kubernetes.rst
pyproject.toml
src/safir/dependencies/arq.py
src/safir/dependencies/http_client.py
tests/dependencies/arq_test.py
tests/dependencies/http_client_test.py

As of FastAPI 0.93.0, FastAPI supports a lifespan async context manager to do startup and shutdown. The part before the yield is run during application startup and the part after the yield is run during application shutdown. The older on_event annotations are now deprecated.
Add a development dependency on FastAPI 0.93.0 and change the test suite uses of on_event annotations to lifespan functions. Update all of the documentation to use the lifespan function instead of on_event handlers.
This change does not bump the Safir FastAPI dependency because Safir's own code still works fine with either method.

DM-41630: Convert to FastAPI lifespan functions

---

changelog.d/20231116_110515_rra_DM_41708a.md
src/safir/testing/kubernetes.py

Avoid reusing the same metadata object when creating a Pod from a Job. Previous versions modified the spec part of the Job when adding additional metadata to the child Pod.

DM-41708: Fix Pod creation from Job in Kubernetes mock

---

changelog.d/20231114_171851_rra_DM_41708a.md
src/safir/testing/kubernetes.py

Add delete, list, and watch support for persistent volume claims to the Kubernetes mock. Fix a few comments on Kubernetes mock methods.

DM-41708: Add more mocks for Kubernetes PVCs

---

src/safir/testing/kubernetes.py

Due to a typo, the annotations from the spec in a Job resource were not being copied to the created Pod in the Kubernetes mock. This bug was introduced in 5.0.0a4.

DM-41820: Fix annotations on Pod created from Job

---

.github/workflows/ci.yaml
.github/workflows/periodic-ci.yaml
changelog.d/20231205_093902_rra_DM_41998.md
pyproject.toml

Add Python 3.12 to the test matrix and declare support for it. This required adding some more ignore rules for deprecations in third-party modules, and one deprecation that affects a test case that is explicitly testing deprecated behavior.

DM-41998: Add support for Python 3.12

---

changelog.d/20231205_164453_rra_DM_42029.md
src/safir/testing/kubernetes.py

Nublado now wants to list nodes with a label selector to support nodeSelector in the prepuller. Add support in the list_node function. Since this requires reconstructing the V1NodeList, store a simple list of nodes in set_nodes_for_test.

DM-42029: Add support for label selectors in mock list_node

---

pyproject.toml

structlog 23.3.0 misclassifies the severity of exceptions as exception rather than error. This is being fixed, so exclude that version rather than change the test suite.

Exclude buggy version of structlog

---

changelog.d/20240116_164958_rra_DM_42527.md
src/safir/middleware/ivoa.py
src/safir/middleware/x_forwarded.py
tests/middleware/ivoa_test.py
tests/middleware/x_forwarded_test.py

Rewrite CaseInsensitiveQueryMiddleware and XForwardedMiddleware as pure ASGI middleware rather than using the Starlette BaseHTTPMiddleware class. The latter seems to be behind some poor error reporting of application exceptions, has caused problems in the past due to its complexity, and is not used internally by Starlette middleware.

DM-42527: Rewrite middleware as pure ASGI middleware

---

changelog.d/20240116_094526_david.irving.md
src/safir/dependencies/gafaelfawr.py
tests/dependencies/gafaelfawr_test.py

Added a FastAPI dependency for retrieving a Gafaelfawr delegated token from the request headers.  This will be used by services consuming client/server Butler, since it needs the delegated token to determine the user's authorization to access a repository.

DM-42190: Add gafaelfawr delegated token FastAPI dependency

---

docs/user-guide/arq.rst
docs/user-guide/database.rst
docs/user-guide/gafaelfawr.rst
docs/user-guide/github-apps/handling-webhooks.rst
docs/user-guide/http-client.rst
docs/user-guide/logging.rst
pyproject.toml
src/safir/dependencies/gafaelfawr.py
tests/dependencies/arq_test.py
tests/dependencies/db_session_test.py
tests/dependencies/gafaelfawr_test.py
tests/dependencies/http_client_test.py
tests/dependencies/logger_test.py

FastAPI now recommends using Annotated to indicate arguments that are set by FastAPI via dependency injection. Among other benefits, this aligns Python's opinion about whether the argument has a default with reality when the function is called outside of a FastAPI context, which can avoid bugs in some edge case situations. It also allows removing special Ruff configuration whitelisting the special FastAPI dependency functions, since Annotated makes the intent obvious.
Also make the same change to route definitions in the test suite.
Adjust the docstring for auth_delegated_token_dependency to use a proper link with anchor text.

DM-42714: Use Annotated for dependency arguments

---

changelog.d/20240219_113514_rra_DM_42937.md
src/safir/datetime.py

parse_isodatetime had a return type that included None, inherited from an earlier version of the function, but it raises an exception if the provided string is not valid and can never return None. Fix the return type to match.

DM-42937: Fix return type of parse_isodatetime

---

.pre-commit-config.yaml
docs/user-guide/gafaelfawr.rst
docs/user-guide/pydantic-redis.rst
pyproject.toml
src/safir/asyncio.py
src/safir/database.py
src/safir/datetime.py
src/safir/testing/kubernetes.py
src/safir/testing/uvicorn.py
tests/dependencies/arq_test.py
tests/dependencies/db_session_test.py
tests/dependencies/gafaelfawr_test.py
tests/dependencies/http_client_test.py
tests/dependencies/logger_test.py
tests/fastapi_test.py
tests/middleware/ivoa_test.py
tests/middleware/x_forwarded_test.py
tox.ini

Update pre-commit dependencies and apply formatting changes. Update test suite for the new call syntax for initializing an httpx AsyncClient with a specific application.

Update dependencies, fix deprecations

---

.pre-commit-config.yaml
docs/user-guide/arq.rst
docs/user-guide/fastapi-errors.rst
pyproject.toml
src/safir/asyncio.py
src/safir/dependencies/gafaelfawr.py
src/safir/pydantic.py
src/safir/testing/kubernetes.py
tests/dependencies/gafaelfawr_test.py
tests/logging_test.py
tests/middleware/ivoa_test.py

Use Ruff for formatting as well as linting, and drop Black for code. Update the version of Black used for documentation and apply the formatting changes it wants to make.

Update Ruff configuration

---

changelog.d/20240312_174906_rra_DM_43288.md
src/safir/dependencies/db_session.py

In the db_session_dependency FastAPI dependency, do database session cleanup in a finally block. This will hopefully ensure that the sessions are cleaned up even on uncaught exceptions, which in turn fixes warnings in test cases in other packages.

DM-43288: Ensure per-request database sessions are closed

---

tests/logging_test.py

The latest pytest uses fancier exception formatting, which confused the check for exception messages with the development profile. Adjust the test accordingly.

Fix exception logging test

---

.github/workflows/ci.yaml
Makefile
changelog.d/20240520_163147_rra_DM_44444.md
docs/user-guide/database.rst
pyproject.toml
src/safir/database.py
tests/database_test.py

When initializing a database engine with create_database_engine or create_sync_session, allow the database password to be a SecretStr instead of a str. This simplifies the call for applications that use Pydantic with SecretStr for secrets.
Fix some places where development dependencies were out of date, and pin requests since the latest version breaks the docker library.

DM-44444: Allow database passwords to be SecretStrs

---

changelog.d/20240521_152707_rra_DM_44444.md
docs/user-guide/datetime.rst
src/safir/datetime.py
tests/datetime_test.py

Add a new safir.datetime.parse_timedelta function that parses a human-friendly syntax for time durations into a datetime.timedelta. The syntax was taken from semaphore and is now also used in the configuration parser for Gafaelfawr.

DM-44444: Add parse_timedelta function to parse durations

---

.github/workflows/ci.yaml
Makefile
tests/conftest.py
tests/database_test.py
tests/dependencies/db_session_test.py
tox.ini

Support the latest tox-docker version and unpin requests, since the incompatibility is now fixed. The latest tox-docker no longer starts Docker images on localhost or with reliable ports, so modify the test setup to use the new tox-docker-exposed environment variables to locate the test PostgreSQL and Redis services.

DM-44444: Update to latest tox-docker

---

pyproject.toml

structlog [uses CalVer](https://github.com/hynek/structlog/blob/main/.github/SECURITY.md) and changes the major version for each year. The structlog developers recommend letting the version float, since the major version has no semantic significance. Backwards compatibility is handled through deprecation warnings.

DM-44444: Remove version cap on structlog

---

.github/workflows/ci.yaml
.github/workflows/periodic-ci.yaml

For all GitHub Actions that do not use a version matrix to ensure that the code itself works with older versions, use Python 3.12 as the Python version, under the principle that tests unrelated to compatibility should follow the latest supported Python version.

DM-44444: Use Python 3.12 for GitHub actions

---

changelog.d/20240520_163147_rra_DM_44444.md
src/safir/dependencies/db_session.py

Following the change to create_database_engine, also allow the password argument to DatabaseSessionDependency.initialize to be a SecretStr.

DM-44606: Allow SecretStr in DatabaseSessionDependency

---

src/safir/arq.py

Make the names of the documented parameters match the prototype.

DM-44606: Fix ArqQueue.enqueue parameter documentation

---

changelog.d/20240605_173149_rra_DM_44606_queue.md
src/safir/arq.py

The initialize method of RedisArqQueue didn't pass the `default_queue_name` argument to `__init__`, so the default queue name was forced to the default. It was set correctly in the pool, but the `enqueue` method overrides the queue name from the pool, so that setting had no effect. This caused messages without an explicit `_queue_name` argument to always be sent to the default queue regardless of the arguments to initialize.

DM-44606: Fix default_queue_name in RedisArqQueue

---

changelog.d/20240605_152335_rra_DM_44606_queue.md
src/safir/gcs.py
tests/gcs_test.py

`gs` is the same as `s3` but specifies Google Cloud Storage. Support either URL format when generating signed URLs in `safir.gcs`.

DM-44606: Support gs URLs in SignedURLService

---

changelog.d/20240530_173040_rra_DM_44606.md
src/safir/dependencies/db_session.py

This was used for Gafaelfawr to share a database engine across all tests for speed, but this technique breaks with current versions of pytest-asyncio and is no longer used or safe to use.

DM-44606: Drop DatabaseSessionDependency.override_engine

---

changelog.d/20240607_112935_rra_DM_44720.md
pyproject.toml
src/safir/slack/blockkit.py
tests/slack/blockkit_test.py
tests/testing/gcs_test.py

Exception classes that call the `BaseException.__init__` method (possibly via `Exception`) with a different number of arguments than the `__init__` method of the derived exception class takes cannot be pickled and unpickled. Since arq uses pickle to record the exception of failed jobs, and we may want such exceptions to be derived from `SlackException` so that we can easily report them to Slack, this is an annoying limitation. The restriction is due to the properties of the default `__reduce__` method on `BaseException` and probably cannot be changed in Python.
Work around this by using the pattern recommended at the end of the discussion in https://github.com/python/cpython/issues/44791, namely avoid calling `BaseException.__init__` entirely. This means we can no longer rely on the …

DM-44720: Support pickling of `SlackException`

---

changelog.d/20240610_113548_rra_DM_44758.md
docs/user-guide/database.rst
src/safir/database.py
tests/database_test.py

Drop support for creating sync database sessions. This was added for vo-cutouts, which used Dramatiq as the task queuing system, since Dramatiq is sync-only. We're standardizing on arq and on async Python in general, and this code will no longer have any known callers after vo-cutouts has been updated.

DM-44758: Drop safir.database.create_sync_session

---

CHANGELOG.md

Remove the note that SecretStr could be passed to `create_sync_session` in the 6.0.0 change log entry, since `create_sync_session` was dropped in that release.

DM-44758: Remove outdated reference in 6.0.0 change log

---

tests/dependencies/gafaelfawr_test.py
tests/dependencies/logger_test.py
tests/logging_test.py

Remove imports from _pytest in the test suite. All of the types for the built-in fixtures are now exported by pytest itself and can be used from there.

DM-45137: Stop importing from _pytest

---

.github/workflows/ci.yaml
.github/workflows/periodic-ci.yaml

Use an environment variable for the default Python version with which to run most actions. Add timeouts to jobs that were missing them. Use the tox-uv plugin uniformly. Fix one place where merge queues weren't handled correctly. Update the periodic CI notification configuration based on proposed template updates.

DM-45137: Update GitHub Actions settings from the template

---

.pre-commit-config.yaml
Makefile
pyproject.toml

Update pre-commit dependencies.
Switch to uv for dependency installation in the Makefile, and add update and update-deps targets for parallelism with FastAPI application packages, even though update-deps doesn't do much (just update uv and pre-commit and run pre-commit autoupdate).

DM-45137: Update dependencies, switch to uv

---

changelog.d/20240712_100038_danfuchs_mobu_github_app.md
src/safir/github/models.py

Needed by mobu to [decide whether or not to create a check suite](https://github.com/lsst-sqre/mobu/blob/6390b7bedbffa61317d570f92cd42500acd8a9c0/src/mobu/handlers/github_ci_app.py#L93).
Confirmed `pull_requests` is an empty array when the check suite event is not associated with an PR:
```json
{
"action": "requested",
"check_suite": {
"id": 25911226694,
"node_id": "CS_kwDOL_KXns8AAAAGCG3xRg",
"head_branch": "main",
"head_sha": "a956612459352be98b651eef40c315a01039b672",
"status": "queued",
"conclusion": null,
"url": "https://api.github.com/repos/lsst-sqre/dfuchs-test-mobu/check-suites/25911226694",
"before": "2504ccedcb5663f87dce23225755e3b26dfc6d40",
"after": "a956612459352be98b651eef40c315a01039b672",
"pull_requests": [
],
```

Add `pull_requests` to `GitHubCheckSuiteModel`

---

pyproject.toml
ruff-shared.toml

Copy ruff-shared.toml from the new version of the project template and extend it with Safir-specific rules. This will hopefully make it easier to update the shared configuration in multiple repositories.

DM-45137: Switch to a shared Ruff configuration

---

changelog.d/20240711_120038_rra_DM_45138.md
docs/user-guide/arq.rst
src/safir/arq.py
tests/dependencies/arq_test.py

Add a new `abort_job` method to instances of `safir.arq.ArqQueue`, which tries to abort a job. If the job has already started, this requires the worker to enable support for aborting jobs.
The mock implementation deletes the job entirely if it hasn't been started, and treats it as if it failed with asyncio.CancelledError if it were already running. This seems to match what arq does with a Redis queue.

DM-45138: Add support for aborting arq jobs

---

changelog.d/20240716_154320_rra_DM_45281.md
docs/documenteer.toml
docs/user-guide/datetime.rst
docs/user-guide/pydantic.rst
src/safir/datetime.py
src/safir/pydantic.py
tests/pydantic_test.py

Take advantage of the new functional validator support in Pydantic v2 and encapsulate custom `timedelta` validation as reusable types. The `SecondsTimedelta` type accept integer or floating-point number of seconds, possibly stringified. The `HumanTimedelta` type accepts the same, plus the duration strings accepted by `parse_timedelta`.
Unfortunately, sphinx-automodapi apparently doesn't recognize `TypeAlias` objects as something for which documentation should be generated, even with `:include-all-objects:`, so references to these new types have to be ignored when generating documentation.

DM-45281: Add new timedelta data types for Pydantic models

---

changelog.d/20240717_101902_rra_DM_45281_queue.md
docs/_rst_epilog.rst
docs/documenteer.toml
docs/user-guide/arq.rst
docs/user-guide/database.rst
docs/user-guide/pydantic.rst
src/safir/pydantic.py
tests/pydantic_test.py

Add new types `safir.pydantic.EnvAsyncPostgresDsn` and `safir.pydantic.EnvRedisDsn`, which validate PostgreSQL and Redis DSNs but rewrite them based on the environment variables set by tox-docker. Programs using these types for their configuration will therefore automatically honor tox-docker environment variables when running the test suite. `EnvAsyncPostgresDsn` also enforces that the scheme of the DSN is compatible with asyncpg and the Safir database support.

DM-45281: Add Pydantic types for Postgres and Redis DSNs

---

src/safir/database/__init__.py
src/safir/database/_connection.py
src/safir/database/_datetime.py
src/safir/database/_initialize.py
tests/database_test.py

Convert `safir.database` from a single-file module to a directory and separate the code into internal modules for ease of maintenance. Upcoming PRs will be adding more code to `safir.database`, and this will avoid dumping all of that code into a single large file.

DM-45281: Break apart `safir.database` for ease of maintenance

---

changelog.d/20240717_212929_rra_DM_45281_queue.md
docs/user-guide/database.rst
src/safir/database/__init__.py
src/safir/database/_retry.py
tests/database_test.py

Add `safir.database.retry_async_transaction`, which retries a function or method a configurable number of times if it fails with a SQLAlchemy exception indicating a problem with the underlying database layer, such as that raised when there is a conflicting transaction.

DM-45281: Add decorator to retry async transactions

---

changelog.d/20240717_220712_rra_DM_45281_queue.md
pyproject.toml
src/safir/database/_connection.py
tests/database_test.py

Allow a Pydantic `Url` to be passed directly to `create_database_engine`. This allows for simpler usage when using the validating Pydantic types for PostgreSQL DSNs.

DM-45281: Allow create_database_engine to take a Url

---

changelog.d/20240717_223040_rra_DM_45281_queue.md
src/safir/slack/webhook.py
tests/slack/webhook_test.py

Allow the URL argument to `SlackWebhookClient` and `SlackRouteErrorHandler` to be given as a `SecretStr` so that applications that get that value from a `SecretStr` field of their configuration don't have to convert it first.

DM-45281: Accept `SecretStr` as the Slack webhook URL

---

changelog.d/20240718_082708_rra_DM_45281_queue.md
docs/user-guide/arq.rst
src/safir/arq.py
tests/arq_test.py

Add a utility function to construct the RedisSettings object used by arq to create a Redis pool.

DM-45281: Add function to build arq RedisSettings

---

.github/workflows/ci.yaml
.github/workflows/periodic-ci.yaml
Makefile
pyproject.toml
tests/conftest.py
tests/database_test.py
tests/dependencies/db_session_test.py
tox.ini

In preparation for converting Safir to a monorepo with multiple PyPI modules and thus the nox build system, switch from tox-docker to testcontainers for testing.

DM-45281: Switch to testcontainers from tox-docker

---

changelog.d/20240814_155547_rra_DM_45779.md
safir/src/safir/dependencies/db_session.py

Allow the database URL argument to `DatabaseSessionDependency`'s initialize method to be a Pydantic `Url`. This allows applications that use `EnvAsyncPostgresDsn` or similar Pydantic types for the database URL in their configuration to not do an explicit conversion.

DM-45779: Allow a `Url` for database session initialization

---

changelog.d/20240814_170047_rra_DM_45779a.md
safir/src/safir/testing/slack.py

Parallel to the constructor of the actual `SlackWebhookClient`, allow `mock_slack_webhook` to take a Pydantic `SecretStr`. This makes integration with test configurations easier.

DM-45779: Allow `mock_slack_webhook` to take `SecretStr`

---

pyproject.toml
ruff-shared.toml

This configuration adds some additional rules that are useful for vertical monorepo repositories using nox, allowing those to be dropped from pyproject.toml.

DM-45794: Update to the current shared Ruff configuration

---

changelog.d/20240816_105321_rra_DM_45818.md
safir/src/safir/uws/_storage.py

The syntax for creating a UWS Availability model was incorrect: the field is notes, not note, and it takes an array of strings.

DM-45818: Fix UWS Availability during errors

---

safir/pyproject.toml

Cap the major version of the safir dependency on safir-logging, following what we did with safir-arq and ensuring that we do not install an incompatible version.

DM-45824: Cap dependency on safir-logging

---

docs/user-guide/uws/write-backend.rst

Add documentation for configuring logging in UWS backend workers. For now, this only involves the normal structlog configuration and therefore only affects the log messages output by the UWS backend code itself. A future revision will also configure arq itself to use JSON logging if appropriate.
Tested by building a new vo-cutouts backend worker container using these instructions and confirming that this configures structlog correctly.

DM-45824: Document logging in Safir UWS workers

---

safir/tests/dependencies/arq_test.py
safir/tests/dependencies/db_session_test.py
safir/tests/dependencies/gafaelfawr_test.py
safir/tests/dependencies/http_client_test.py
safir/tests/dependencies/logger_test.py
safir/tests/fastapi_test.py
safir/tests/middleware/ivoa_test.py
safir/tests/middleware/x_forwarded_test.py
safir/tests/slack/webhook_test.py
safir/tests/uws/conftest.py
safir/tests/uws/job_api_test.py

The latest version of httpx and mypy no longer needs `type: ignore` markers when creating the transport for testing applications.

DM-46034: Remove now-unnecessary `type: ignore` markers

---

safir/pyproject.toml

pytest-asyncio is changing the default loop lifetime for fixtures and now warns about not explicitly setting a default. Set the default for Safir to the new value.

DM-46034: Add new pytest-asyncio configuration

---

docs/user-guide/database/initialize.rst
safir/tests/dependencies/db_session_test.py

Update the documentation for defining a database schema and one test case to use the new `DeclarativeBase` inheritance syntax. Add a documentation link to the current way of defining ORM models with SQLAlchemy.

DM-46034: Remove remaining declarative_base references

---

changelog.d/20241009_155401_danfuchs_vo_models_type_compatibility.md
safir/pyproject.toml
safir/src/safir/uws/_models.py
safir/src/safir/uws/_storage.py

Now that [there's a py.typed in vo-models](https://github.com/spacetelescope/vo-models/commit/956c049c1c1782efbe0e5e37fb9f0a479704e53b), `mypy` is showing some incorrect usage.
Note that a version of `vo-models` with [these changes](https://github.com/spacetelescope/vo-models/compare/main...fajpunk:vo-models:export-names?expand=1) is needed to get a clean typecheck.

DM-44365: `vo-models` integration fixes

---

docs/user-guide/metrics/index.rst
safir/src/safir/metrics/__init__.py
safir/src/safir/metrics/_models.py
safir/tests/event_manager_test.py

This is admittedly somewhat nasty, and depends on a deprecated Pydantic feature (`json_encoders` in model config), but I think it's the only way to be able to serialize time deltas directly on `AvroBaseModel` models.
[This](https://github.com/marcosschroh/dataclasses-avroschema/blob/b8f7b8dfa877fea58887e4cd34d34e2ab6551afa/dataclasses_avroschema/fields/fields.py#L1000-L1038) is the code that enables this is [dataclasses-avroschema](https://github.com/marcosschroh/dataclasses-avroschema).  It requires explicitly that:
* The custom type has a `__get_pydantic_core_schema__` method
* The model has a (deprecated) `json_encoders` config set
* This `json_encoders` dict maps the custom type to a function that is itself one of the types that is [natively supported by …

DM-45522: Use `timedelta`s in event payloads

---

safir/pyproject.toml
safir/tests/pydantic_test.py

One specific test of Safir uses `datetime.utcnow`, which is deprecated. Move the warning suppression out of `pyproject.toml` to an annotation on that function, since we'll be keeping that test until the upstream function is removed entirely.

DM-46821: Move warning suppression to an annotation

---

changelog.d/20241021_091054_rra_DM_47011.md
safir/src/safir/metrics/_config.py
safir/tests/metrics/config_test.py

Allow and ignore extra attributes to `MetricsConfiguration` when metrics are disabled. This allows passing a partial metrics configuration even when they are disabled, which simplifies the structure of Phalanx configurations based on dumping the Helm values into a YAML configuraiton file.

DM-47011: Allow extra values to disabled metrics config

---

changelog.d/20241022_002510_steliosvoutsinas_DM_47027.md
safir/src/safir/uws/_dependencies.py
safir/tests/uws/conftest.py
safir/tests/uws/post_params_test.py

**Summary**
PR addresses issue where the uws_post_params dependency did not correctly read in list parameters, i.e. multiple occurrences of the same param. The fix was to change items() to multi_items() on the request.form() object.
A test has been added which sets up a test endpoint which returns the params passed in to the request, and exercises it with a request with multiple of the same param.

DM-47027: Change ws_post_params_dependency to handle multiple occurrences of the same param

---

docs/documenteer.toml
docs/user-guide/pydantic-redis.rst

The first example of using `PydanticRedisStorage` does not use keyword arguments, but keyword arguments are required. Fix the documentation to match the code. Reported by @Fireye04.

Fix `PydanticRedisStorage` documentation

---

changelog.d/20241106_103655_danfuchs_metrics_timedelta_builtin.md
docs/user-guide/metrics/index.rst
safir/pyproject.toml
safir/src/safir/metrics/__init__.py
safir/src/safir/metrics/_models.py
safir/tests/metrics/event_manager_test.py

Require a version of `dataclasses-avroschema` with native `timedetla` support, and remove the `EventDuration` custom pydantic type.

DM-45522 metrics: native `timedelta` support

---

docs/user-guide/database/datetime.rst
docs/user-guide/database/schema.rst
docs/user-guide/pydantic.rst

Clarify why all times are stored in databases in timezone-naive fields even if the database supports timezone-aware times. Fix a missing backslash when describing how to check schema migrations. Fix one place where a Safir function was mistakenly said to be provided by Pydantic.

DM-47262: Minor documentation fixes

---

changelog.d/20241112_163814_rra_DM_47262.md
safir/src/safir/pydantic/_types.py
safir/tests/pydantic_test.py

Add serializers to `HumanTimedelta` and `SecondsTimedelta` that serialize those Pydantic fields to a float number of seconds instead of ISO 8601 durations. This means those data types now can be round-tripped (serialized and then deserialized to the original value), whereas before they could not be. This also avoids ISO 8601 durations in service replies that use models including those types.
Fix parsing of stringified floating-point number of seconds for `SecondsTimedelta`, which previously was truncating to an integer number of seconds.

DM-47262: Add serializers for *Timedelta types

---

changelog.d/20241113_165421_rra_DM_47262b.md
docs/user-guide/database/schema.rst
docs/user-guide/database/testing.rst
safir/src/safir/database/__init__.py
safir/src/safir/database/_initialize.py
safir/tests/database_test.py

Document how to test the current SQLAlchemy ORM schema against the Alembic migrations to catch schema changes that have no corresponding migration. Document creating an initial Alembic migration that creates the initial schema. Add the `safir.database.drop_database` utility function to make it easier to write that test case.

DM-47262: Document testing Alembic config against schema

---

changelog.d/20241113_152723_rra_DM_47262a.md
docs/documenteer.toml
docs/user-guide/datetime.rst
docs/user-guide/pydantic.rst
pyproject.toml
safir/src/safir/datetime/_parse.py
safir/src/safir/pydantic/__init__.py
safir/src/safir/pydantic/_types.py
safir/src/safir/pydantic/_validators.py
safir/tests/datetime_test.py
safir/tests/pydantic_test.py
safir/tests/uws/errors_test.py

Change `parse_isodatetime` and `normalize_isodatetime` to support exactly the formats specified by the IVOA DALI standard (and fix incorrect references to UWS). This means supporting timestamps without the time component and making the trailing Z optional, but requiring seconds be present if the time portion is present. This should not interfere with the other uses, such as parsing Kubernetes timestamps.
Add new data types `UtcDatetime` and `IvoaIsoDatetime` that are now the preferred way to use the normalization functions in models. The former accepts any format Pydantic supports but coerces it to UTC and timezone-aware. The latter accepts only the formats supported by `parse_isodatetime`. Document those data types instead of the normalization functions, although the normalization …

DM-47262: Fix IVOA DALI timestamp parsing, add data types

---

changelog.d/20241119_132629_danfuchs_fix_metrics_timedelta.md
docs/user-guide/metrics/index.rst
safir/pyproject.toml
safir/src/safir/metrics/_models.py
safir/tests/metrics/event_manager_test.py

This is two bug fixes:
* One in this lib where validation of `EventPayload` models was broken for unions
* One in [dataclasses-avroschema](https://github.com/marcosschroh/dataclasses-avroschema/pull/797) where timedeltas could not be serialized in Avro unions

`timedelta` can now be used a member of a union field in an EventPayload

---

changelog.d/20241122_164744_danfuchs_metrics_publishing_is_slow.md
safir/src/safir/metrics/_event_manager.py

`aoikafka` publishes messages via a background task and provides futures to wait for actual delivery. `faststream` waits on these futures by default. We don't need to wait for publishing app metrics.
Initial performance tracing of Gafaelfawr showed 5-20ms taken up when publishing an event, with this patch, it seems to take ~0.3ms.
Thanks to @rra for finding this performance issue!

DM-47771: metrics: don't wait for kafka messages to be delivered

---

docs/user-guide/database/session.rst
safir/src/safir/database/_connection.py

Importing from `sqlalchemy.future` and passing `future=True` when creating sessions is no longer required since we require SQLAlchemy 2.0 or later.

DM-47769: Remove obsolete SQLAlchemy future flags

---

changelog.d/20241125_140320_rra_DM_47796.md
safir/pyproject.toml

Add alembic as a dependency to the `safir[uws]` extra. That extra currently must duplicate all of the dependencies of `safir[db]`, since it loads the Safir database support. This can be dropped once the UWS code in Safir is a front-end for Wobbly.

DM-47796: Add alembic dependency to uws extra

---

CHANGELOG.md

Use imperative tense and rewrite some change log entries for a user instead of Safir developer audience.

DM-47789: Reword change log for 7.0.0

---

docs/user-guide/database/pagination.rst
safir/src/safir/database/__init__.py
safir/src/safir/database/_pagination.py
safir/tests/database_test.py

Fix several issues with pagination support uncovered by converting Gafaelfawr to the new approach.
* Document the type parameterization of cursors.
* Document the need to implement `from_entry` for cursors derived from `DatetimeIdCursor`.
* Move cursor parsing into the body of the suggested handler function since FastAPI cannot validate complex models as query parameters.
* Change the pagination exception to a new `InvalidCursorError` instead of `ValueError` since parsing will be done in the handler body and needs to throw an error that can be automatically handled and converted to a 422 HTTP status code.
* Rename `PaginatedLinkData` to `PaginationLinkData` for more correct grammar.
* Drop `DeclarativeBase` from the prototype of `query_object` because tuples are not covariant and this …

DM-47789: Fix various issues with pagination support

---

changelog.d/20241126_175555_steliosvoutsinas_DM_47459.md
safir/src/safir/middleware/ivoa.py
safir/tests/middleware/ivoa_test.py

**Summary**
Most IVOA specifications expect service providers to support case-insensitive params, including for `application/x-www-form-urlencoded` POST requests. This PR adds a middleware class `CaseInsensitiveFormMiddleware` which parses the form params and converts them to lowercase.
As part of the changes I've also added a couple tests for the new middleware class, and in the process have broken the `middleware/ivoa_test.py` tests into smaller individual tests. I can revert that if the single test is preferred.
**Tests**
- Added unit tests and tested via nox
- Tested SIAv2 app with new middleware on data-dev

DM-47459: Added middleware for converting form post params to lowercase

---

safir/src/safir/database/_pagination.py

Sphinx really struggles to resolve references in inherited docstrings when they reference the context of the upstream module from which they are inherited. Use absolute references in the docstrings for the pagination code in the hope that this will be friendlier to downstream projects using Sphinx.

DM-47789: Make pagination docs friendlier to subclasses

---

safir/src/safir/database/_pagination.py

Fully-qualify more type references in pagination docstrings to help downstream projects that use Sphinx.

DM-47789: Qualify more types in pagination docstrings

---

docs/user-guide/ivoa.rst
safir/src/safir/middleware/ivoa.py

Document `CaseInsensitiveFormMiddleware` in the user guide alongside `CaseInsensitiveQueryMiddleware`.
Mark the methods of `CaseInsensitiveFormMiddleware` as internal to the class, since they aren't intended as an exposed API.

DM-47769: Add documentation of CaseInsensitiveFormMiddleware

---

changelog.d/20241203_132727_rra_DM_47928.md
docs/user-guide/uws/define-inputs.rst
safir/src/safir/uws/__init__.py
safir/src/safir/uws/_app.py
safir/src/safir/uws/_dependencies.py
safir/src/safir/uws/_handlers.py

Convert the UWS support to the newly-added case-insensitive form middleware, which removes the need for annoying workarounds for case-insensitive form parameters. Update the application documentation accordingly.

DM-47928: Use case-insensitive form middleware for UWS support

---

changelog.d/20241205_130111_danfuchs_metrics_events_unittest_support.md
docs/documenteer.toml
docs/user-guide/metrics/index.rst
safir/src/safir/metrics/__init__.py
safir/src/safir/metrics/_config.py
safir/src/safir/metrics/_event_manager.py
safir/src/safir/metrics/_testing.py
safir/tests/metrics/config_test.py
safir/tests/metrics/event_manager_test.py
safir/tests/metrics/mock_publisher_test.py

Add a `MockEventManager` that creates `MockPublishers` which are no-op publishers that record all published payloads. This is returned from the config factory function when `enabled` is `False` and a new config key, `mock`, is `True`.
Payloads are recorded to a list with mixed-in assertion helpers.

DM-47764: App metrics unit testing helpers

---

changelog.d/20241211_163506_rra_DM_47986.md
noxfile.py
safir/pyproject.toml

The main safir PyPI module was constraining the major version of safir-logging and safir-arq, which would break the new UWS support by pinning too old of a version of safir-arq. Those major version constraints are too easy to forget to update, so remove them and instead have Safir pull in the latest version.
Unfortunately, either approach here potentially creates problems down the road. Hopefully this will be the approach that creates fewer issues.

DM-47986: Fix dependency constraints on Safir modules

---

.github/dependabot.yml
CHANGELOG.md
changelog.d/20241211_163506_rra_DM_47986.md
safir/pyproject.toml

Collect change log for 6.0.1 release. Update major version pins on some dependencies and fix the dependabot configuration to detect dependency updates, which was broken when Safir was converted to nox.

DM-47986: Prepare 6.0.1 release

---

safir/tests/support/kafka/data/generate-kafka-secrets.bash

Under Python 3.13, Kafka tests were failing because no key usage extension was defined on the CA certificate. Add the appropriate flag to `openssl` to define an appropriate key usage extension for the CA.

DM-48098: Add key usage to the Kafka test CA

---

pyproject.toml

We're now using Ruff for reformatting, so the file ignore patterns for Black are no longer used. Delete them from `pyproject.toml`.

DM-48173: Remove now-unneeded Black configuration

---

docs/user-guide/metrics/index.rst

Update the documentation for how to set up metrics events to use `metrics_configuration_factory` and do not bother to set `METRICS_EVENTS_TOPIC_PREFIX` in the mock case (it's not needed). Move `model_config` to the top of the class to make it somewhat more visible, following the coding style I've been trying to adopt elsewhere.

DM-48173: Update metrics configuration documentation

---

docs/user-guide/database/pagination.rst
safir/src/safir/database/__init__.py
safir/src/safir/database/_pagination.py
safir/tests/database_test.py

`PaginatedQueryRunner` has a separate `query_count` method to return the count, but since the total entry count isn't included in the `PaginatedList` data structure, it's annoying to pass between components of a service. Either the result plus the count have to be returned as a tuple, or the service has to add its own data structure to wrap `PaginatedList`.
Avoid this by introducing a `CountedPaginatedQueryRunner` and a corresponding `CountedPaginatedList` that always includes a `count` attribute. This can be used by services such as Gafaelfawr that always want to count the total number of entries, either because the table is small or because the count can always be satisfied from the table indices.

DM-48173: Add abstraction for counted paginated queries

---

docs/documenteer.toml

Point to the correct Sphinx bug to explain why we're excluding `Path` from Sphinx nitpicks.

DM-48199: Update comment for Sphinx Path exclusion

---

docs/user-guide/database/initialize.rst
docs/user-guide/database/schema.rst

Avoid using the `run_with_asyncio` decorator for the init command-line command, since Alembic doesn't like to run inside an existing event loop. Instead, recommend using an async helper function and `asyncio.run` from the start so that adding Alembic support is simple.

DM-48408: Fix documentation of database initialization

---

CHANGELOG.md
safir/src/safir/sentry/_exceptions.py
safir/src/safir/slack/blockkit.py

In `SlackWebException.from_exception` and `SentryWebException.from_exception`, the message of the created `SlackWebException` is based on the type name and message of the underlying exception. However, some underlying exceptions, such as timeout errors, may have no message. In that case, drop the trailing colon and space and set the message of `SlackWebException` and `SentryWebException` to only the name of the type of the underlying exception.

DM-48760: Simplify if underlying exception has no message

---

changelog.d/20250206_121830_rra_DM_48819.md
docs/_rst_epilog.rst
docs/user-guide/arq.rst
docs/user-guide/database/dependency.rst
docs/user-guide/database/schema.rst
docs/user-guide/database/testing.rst
docs/user-guide/gafaelfawr.rst
docs/user-guide/http-client.rst
docs/user-guide/kubernetes.rst
docs/user-guide/sentry.rst
docs/user-guide/uws/create-a-service.rst
docs/user-guide/uws/testing.rst
safir/src/safir/asyncio/_multiqueue.py
safir/src/safir/dependencies/arq.py
safir/src/safir/dependencies/db_session.py
safir/src/safir/dependencies/http_client.py
safir/src/safir/redis/_storage.py
safir/src/safir/testing/kubernetes.py
safir/tests/conftest.py
safir/tests/dependencies/arq_test.py
safir/tests/dependencies/http_client_test.py
safir/tests/uws/conftest.py

In all places where the function returns an async generator rather than an async iterator (which is all cases in Safir), correctly type them as returning `AsyncGenerator`, not `AsyncIterator`. In most cases this won't matter, but `AsyncGenerator` has additional methods such as `aclose`.

DM-48819: Use AsyncGenerator over AsyncIterator

---

changelog.d/20250207_155019_rra_DM_48838.md
safir/src/safir/testing/kubernetes.py

Add create, delete, read, and list (with watches) support for `ServiceAccount` objects to the mock Kubernetes API.

DM-48838: Add ServiceAccount to Kubernetes mock

---

changelog.d/20250210_173334_rra_DM_48838.md
docs/user-guide/kubernetes.rst
safir/src/safir/testing/kubernetes.py

Refactor the Kubernetes mock to move more code into shared internal methods, most notably publication of internal events that is used for the watch support. Add support for a callback after object creation that can be used for things like creating the default service account for a namespace when the namespace is created.

DM-48838: Add object creation callbacks to Kubernetes mock

---

safir-arq/src/safir/arq/_models.py
safir/src/safir/github/models.py
safir/src/safir/models/_errors.py

All of the enums that used dual inheritance from `str` and `Enum` had values matching their names, so they could safely be converted to `StrEnum`. Do so to use the more standard class.

DM-48838: Switch to StrEnum

---

safir/src/safir/github/webhooks.py

Convert additional enums inheriting from `str` and `Enum` to `StrEnum` that were missed in the previous change.

DM-48838: Convert more enums to StrEnum

---

safir/src/safir/fastapi/_errors.py
safir/src/safir/sentry/_exceptions.py

Add missing `__all__` variable to `safir.sentry._exceptions` and reformat the `__init__` method of `SentryException`.

DM:48838: Add __all__ to safir.sentry._exceptions

---

safir/src/safir/asyncio/_multiqueue.py
safir/src/safir/sentry/_helpers.py
safir/src/safir/slack/blockkit.py

Replace calls to `current_datetime(microseconds=True)` with the standard `datetime.now(tz=UTC)`, which was added in 3.11 and is shorter and more familiar.

DM-48838: Use current_datetime in fewer places

---

docs/user-guide/pydantic.rst
safir/src/safir/kafka/_kafka_config.py
safir/src/safir/kafka/_schema_registry_config.py
safir/src/safir/metrics/_config.py
safir/src/safir/pydantic/_camel.py
safir/tests/support/alembic.py

For Pydantic classes with a custom model configuration, set the model configuration at the start of the class instead of at the end. It changes a lot of behavior, and putting it at the top makes it more obvious.

DM-48838: Move model_config to the start of classes

---

docs/user-guide/sentry.rst

Use a more succinct syntax for named links, use `Config` instead of `Configuration` for a configuration class, enforce newlines between sentences in a few more places, and use different markup for file names.

DM-48838: Minor editing of the Sentry documentation

---

safir/tests/dependencies/db_session_test.py

Since the 2.0.0 release, there is no longer a need to impor the new sqlalchemy API from sqlalchemy.future.

DM-48838: Avoid sqlalchemy.future

---

CHANGELOG.md
changelog.d/20250206_121830_rra_DM_48819.md
changelog.d/20250207_155019_rra_DM_48838.md
changelog.d/20250210_173334_rra_DM_48838.md
safir/pyproject.toml

Collect the change log for the 6.3.0 release. Put a lower bound on the FastAPI dependency to ensure that an ancient version of FastAPI with no bounded Pydantic dependency is not eligible.

DM-48838: Prepare 6.3.0 release

---

.github/workflows/ci.yaml
.github/workflows/periodic-ci.yaml
changelog.d/20250219_101859_rra_DM_49036.md
docs/user-guide/uws/write-backend.rst
safir-arq/pyproject.toml
safir-logging/pyproject.toml
safir/pyproject.toml

Now that the stack containers have switched to Python 3.12, drop support for Python 3.11. Use Python 3.13 for the portions of GitHub Actions that do not need to use a matrix of Python versions.

DM-49036: Increase minimum Python version to 3.12

---

docs/documenteer.toml
safir-arq/src/safir/arq/uws.py
safir/src/safir/asyncio/_multiqueue.py
safir/src/safir/asyncio/_run.py
safir/src/safir/database/_pagination.py
safir/src/safir/database/_retry.py
safir/src/safir/dependencies/metrics.py
safir/src/safir/kafka/_manager.py
safir/src/safir/metrics/_event_manager.py
safir/src/safir/metrics/_testing.py
safir/src/safir/pydantic/_camel.py
safir/src/safir/pydantic/_validators.py
safir/src/safir/redis/_storage.py
safir/src/safir/uws/_models.py

Use the new syntax added in Python 3.12 for generics. This results in better typing in mypy, which required a few added casts because the typing of metrics publishers is dynamic and somewhat strange.
Sphinx unfortunately has bugs generating documentation for generics when `from __future__ import annotations` is present, so remove that line from several modules so that the documentation will generate properly.
autodoc_pydantic is unfortunately very buggy when used with `Annotated`, which required several additional ignore rules and probably results in poor documentation for some Pydantic models.

DM-49036: Switch to new syntax for generics

---

docs/documenteer.toml
safir/src/safir/metrics/_config.py
safir/src/safir/metrics/_testing.py
safir/src/safir/pydantic/_types.py
safir/src/safir/uws/_config.py

Declare type aliases with the new `type` keyword instead of using the `TypeAlias` type. Sphinx unfortunately cannot currently cope with these, so more exclusions were required.

DM-49036: Use type instead of TypeAlias

---

changelog.d/20250224_140058_danfuchs_update_github_pr_model.md
safir/src/safir/github/models.py

The Mobu CI integration wants to run against all of the files in a PR.
It is planning on using the [list pull request files](https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#list-pull-requests-files) API endpoint, which takes a PR number.
We get this PR number back in the check run info response.

DM-49117: Add `number` to GitHubCheckRunPrInfoModel

---

.github/workflows/ci.yaml
.github/workflows/periodic-ci.yaml
LICENSE
safir-arq/pyproject.toml
safir-logging/pyproject.toml
safir/pyproject.toml
safir/src/safir/metrics/_config.py
safir/tests/conftest.py

Use v3 of lsst-sqre/build-and-publish-to-pypi, which uses uv to build and publish the package instead of the PyPA build tool and twine. Update the license metadata in the packages to follow PEP 639.

DM-49735: Update license metadata and PyPI publish action

---

changelog.d/20250411_171300_rra_DM_50095.md
docs/_rst_epilog.rst
docs/user-guide/database/index.rst
safir/src/safir/database/_connection.py

The Qserv Kafka bridge needs to speak MySQL rather than PostgreSQL to the Qserv frontend. Add support for rewriting `mysql` DSNs to `mysql+asyncmy`, similar to the existing rewrite of `postgresql` DSNs, to `create_async_engine`, and add support for a `connect_args` parameter to pass arguments to the underlying database driver. The latter is needed to configure TLS parameters with asyncmy.

DM-50095: Add asyncmy and connect_args support for databases

---

changelog.d/20250505_134035_rra_DM_50527.md
docs/user-guide/database/dependency.rst
docs/user-guide/database/session.rst
safir/src/safir/database/_connection.py
safir/src/safir/dependencies/db_session.py

Pass the `max_overflow`, `pool_size`, and `pool_timeout` arguments down to the engine creation. Add all of the `create_database_engine` to the `initialize` method of `DatabaseSessionDependency` as well, and note them in the documentation.
This change still takes the approach of declaring each parameter separately rather than passing all unknown parameters through to SQLAlchemy. This results in better type checking at the cost of having to change Safir for each new supported parameter. The code is constructed to not pass a parameter, even with a value of `None`, if that parameter was not set, mostly out of paranoia that some engine parameter may give a special meaning to `None`.

DM-50527: Allow configuration of database pool size

---

safir/pyproject.toml
safir/src/safir/click/_help.py

Use `click.Group` instead of `click.MultiCommand` and update the minimum Click version to 8.2.0 to avoid needing to worry about backward-compatibility.

Update for Click 8.2.0

---

changelog.d/20250521_132914_rra_DM_50964.md
docs/user-guide/pydantic-redis.rst
safir/src/safir/redis/_storage.py
safir/tests/redis_test.py

In the `store` method of `PydanticRedisStorage` and `EncryptedPydanticRedisStorage`, support some of the Pydantic serialization options so that applications can reduce the size of serialized objects with large numbers of optional fields. Document that normally these flags should not be used because the default serialization is more future-proof.
This support is desired to reduce the size of query objects stored by the Qserv Kafka bridge with wide returns, since the optional fields for the per-column schema definition otherwise can consume over 100KB of space in the serialized object.

DM-50964: Support serialization options for Redis storage

---

.github/workflows/ci.yaml
.github/workflows/periodic-ci.yaml

At 10 minutes we just exceeding the timeout for the docs build and upload.

Increase docs job timeout to 15 minutes

---

noxfile.py
safir/pyproject.toml
safir/tests/data/database/v1/alembic.ini
safir/tests/data/database/v2/alembic.ini
safir/tests/database_test.py

Fix periodic test failures and warnings with new versions of dependencies, as follows:
- pytest-asyncio 1.0.0 has removed the `event_loop` fixture. Adjust the test suite accordingly.
- Alembic 1.16.0 has added `path_separator`, replacing `version_path_separator`, and warns if it is not present in the configuration. Update the test configuration accordingly.

Adjust for changes in dependencies

---

.pre-commit-config.yaml
docs/documenteer.toml
safir-arq/src/safir/arq/_models.py
safir/src/safir/metrics/_testing.py
safir/src/safir/sentry/_helpers.py
safir/src/safir/uws/_config.py
safir/tests/uws/job_api_test.py

Update pre-commit dependencies and fix several issues uncovered by testing with new dependencies.
For Ruff, adjust the logic around `None` values in Sentry event fingerprints, simplify code in a test to pass Ruff 0.12, and add a missing `__hash__` setting for `NOT_NONE`.
For Sphinx, drop intersphinx for Redis since it's no longer maintained and add Redis symbols to the ignore list. Remove duplicate dataclass attribute documentation since Sphinx now handles this correctly by default. Fix the names of vo-models symbols to match their exposed intersphinx names.

Fix issues arising from dependency updates

---

.github/workflows/periodic-ci.yaml

Get the full version history so that setuptools-scm can get proper version numbers in the periodic CI jobs. Otherwise, it will install the last released safir-arq package.

Get proper version numbers in periodic CI

---

changelog.d/20250709_154628_danfuchs_HEAD.md
docs/_rst_epilog.rst
safir/src/safir/github/models.py
safir/tests/github/webhooks_test.py

Mobu CI is going to use [`pull_request` events](https://docs.github.com/en/webhooks/webhook-events-and-payloads#pull_request) instead of `check_suite` and `check_run` events. It needs to check out the repo at a specific ref. The most specific ref in the `pull_request` event is the commit hash of the last commit to the head branch of the PR, available at `.pull_request.head.sha`.
Goes with [this Mobu PR](https://github.com/lsst-sqre/mobu/pull/465)

DM-51751: Add `head` value to GitHubPullRequestModel

---

changelog.d/20250625_132809_danfuchs_HEAD.md
docs/user-guide/metrics/index.rst
pyproject.toml
ruff-shared.toml
safir/pyproject.toml
safir/src/safir/metrics/__init__.py
safir/src/safir/metrics/_config.py
safir/src/safir/metrics/_constants.py
safir/src/safir/metrics/_event_manager.py
safir/src/safir/metrics/_exceptions.py
safir/src/safir/metrics/_models.py
safir/src/safir/testing/containers/_kafka.py
safir/tests/conftest.py
safir/tests/kafka/kafka_config_test.py
safir/tests/kafka/schema_manager_test.py
safir/tests/metrics/config_test.py
safir/tests/metrics/event_manager_test.py
safir/tests/support/kafka.py
safir/tests/support/metrics.py

This is a lot of diff, and I'm glad to split it into separate PRs if we want, but none of it makes any sense alone. I tried to make the individual commits a good guide for what's going on, but again, I'm glad to split any of those commits off into other PRs.
If the underlying app metrics infrastructure is degraded, like if Kafka or the Schema Registry are not available, the Safir app metrics code now tries very hard to not crash or your instrumented application.
Instead of of raising exceptions, it will log error-level messages and put itself into an error state. Once in this error state, it will not even try to interact with any underlying infrastructure, which means it will not even try to send metrics.
It will instead only log error messages.
If this happens during initialization, you …

DM-48229: App metrics application resiliency

---

README.md
docs/_rst_epilog.rst
docs/index.rst
docs/user-guide/index.rst
docs/user-guide/set-up-from-template.rst
docs/user-guide/template-manual.rst
safir-arq/README.md
safir-logging/README.md

There are some steps users should take after creating a new project via Squarebot, so devote the main tutorial page to that and move the manual process into a separate page with some duplication of steps. Update both for the current templates (uv, Ruff instead of Black, new dependency management method).
Update the README files to point to Phalanx in general and list the Rubin Science Platform and Roundtable as separate cases. Drop the link to the old Roundtable site, since that's no longer useful to users.
Drop the list of Safir features from the README. It's out of date and largely duplicates the documentation, which is already linked from the README.

DM-51521: Revise documentation for current templates

---

changelog.d/20250728_114205_rra_DM_51984.md
docs/user-guide/kafka/testing.rst
safir/pyproject.toml
safir/src/safir/metrics/_event_manager.py
safir/tests/kafka/kafka_config_test.py
safir/tests/support/kafka.py

Close FastStream brokers with `stop` instead of `close` and require FastStream 0.5.44 or later to avoid deprecation warnings.

DM-51984: Use stop instead of close for FastStream

---

changelog.d/20250729_181448_danfuchs_HEAD.md
docs/_rst_epilog.rst
docs/user-guide/arq.rst
docs/user-guide/metrics/index.rst
safir/src/safir/metrics/__init__.py
safir/src/safir/metrics/_arq.py
safir/tests/conftest.py
safir/tests/metrics/arq_metrics_test.py

You can now instrument your [arq](https://github.com/python-arq/arq) jobs to emit an `arq_job_run` app metric with a `queue` tag and a `time_in_queue` field. You can use this to help you decide if and when you need to add more workers.
To enable this, you need to:
* Add app metrics configuration to your app
* Add `queue` to the list of fields in the Sasquatch app metrics configuration
* Create a `safir.metrics.EventManager` and pass it to `safir.metrics.initialize_arq_metrics` in your `WorkerSettings.on_startup` function.
* Generate an `on_job_start` function by passing a queue name to `safir.metrics.make_on_job_start`.
Make sure you shut this event manager down cleanly in your shutdown function.
Using this in an app looks like [this PR](https://github.com/lsst-sqre/noteburst/pull/126/) …

DM-51912: arq - metrics

---

changelog.d/20250805_150146_danfuchs_HEAD.md
safir/src/safir/metrics/_arq.py

The arq time-in-queue metric is comparing the current time at whole second precision, with the arq enqueued time at millisecond precision, resulting in negative values.
Fix this by not truncating the current time when calculating the value.

metrics - fix arq time-in-queue metric

---

changelog.d/20250821_164709_rra_DM_52238a.md
safir/pyproject.toml

Updating dependencies on vo-cutouts tried to downgrade the Google API modules to an ancient version because they pin an older major version of cachetools and the latest version of tox depends on the new version. Ensure this cannot happen by setting a version floor for the Google API modules.

DM-52238: Add lower bounds on Google modules
