.github/workflows/ci.yaml, CHANGELOG.rst
- Set release date
- Add Python 3.10 to the test matrix
=> [DM-32401] Release 2.0.2

.github/workflows/ci.yaml, CHANGELOG.rst, Makefile, docs/api.rst, docs/conf.py, docs/database.rst, docs/dev/development.rst, docs/index.rst, setup.cfg, src/safir/database.py, src/safir/dependencies/db_session.py, tests/database_test.py, tests/dependencies/db_session_test.py, tox.ini
Import and adapt the database dependency from Gafaelfawr and the
database setup and utility functions from Gafaelfawr and vo-cutouts.
Add a new db extra that installs the necessary prerequisites.
=> [DM-33604] Add database support code

CHANGELOG.rst, docs/database.rst, src/safir/database.py, tests/database_test.py
Add datetime_from_db and datetime_to_db helper functions to the
safir.database module, plus tests and documentation.
=> [DM-33604] Add datetime helper functions to database layer

CHANGELOG.md
- Fix a typo in `CHANGELOG.md`
- Set the release date for 3.6.0
=> DM-37760: Prepare for 3.6.0 release

CHANGELOG.md
Add the change log entry for the new schema support in initialize_database.
=> DM-38170: Finalize changes for 3.7.0

CHANGELOG.md, docs/documenteer.toml, pyproject.toml
- Stamp 4.0.0 release in change log
- Update isort configuration to use "black" profile (no effects)
=> DM-38773: Prepare 4.0.0 release

CHANGELOG.md, docs/documenteer.toml, docs/user-guide/set-up-from-template.rst
Fix several redirects caught by a links check. Add new Pydantic noise to nitpick_ignore.
=> Fix minor documentation build issues

.pre-commit-config.yaml, src/safir/asyncio.py
- Update pre-commit dependencies
- Remove now-unneeded mypy annotation
=> Update and adjust for dependencies

.pre-commit-config.yaml, safir/src/safir/uws/_service.py
Update to the latest Ruff in pre-commit and apply a couple of fixes (rewrites to use min) that it wishes to do.
=> DM-45824: Update to the latest Ruff

.github/workflows/ci.yaml, CHANGELOG.md, changelog.d/20240802_155256_rra_DM_45575.md, changelog.d/20240814_155547_rra_DM_45779.md, changelog.d/20240814_170047_rra_DM_45779a.md, changelog.d/20240816_105321_rra_DM_45818.md, changelog.d/20240816_132729_rra_DM_45824.md
Collect change log for the 6.3.0 release.
=> DM-45824: Prepare 6.3.0 release

CHANGELOG.md
The release is actually going out today.
=> DM-45824: Fix release date for 6.3.0

noxfile.py
The init and venv-init sessions had not been updated to install the additional Safir packages. Do so, and add all of the optional dependencies for Safir rather than only the dev optional dependencies.
=> DM-46034: Fix nox init and venv-init sessions

CHANGELOG.md
Add a change log for the upcoming 6.4.0 release.
=> DM-46034: Prepare 6.4.0 release

README.md, changelog.d/20240919_141153_danfuchs_kafka.md, docs/api.rst, docs/documenteer.toml, docs/user-guide/index.rst, docs/user-guide/kafka.rst, safir/pyproject.toml, safir/src/safir/kafka/__init__.py, safir/src/safir/kafka/_config.py, safir/tests/conftest.py, safir/tests/constants.py, safir/tests/kafka_test.py, safir/tests/support/kafka/container.py, safir/tests/support/kafka/data/generate-kafka-secrets.bash
For metrics events publishing, we've decided that we want to connect directly to Kafka. Here are some helpers to do that from Safir apps.
The Sasquatch/Phalanx docs that go with this are coming soon...
=> DM-45522: Kafka connection helpers

changelog.d/20241002_170409_danfuchs_metrics_events2.md, docs/_rst_epilog.rst, docs/api.rst, docs/documenteer.toml, docs/user-guide/index.rst, docs/user-guide/kafka/index.rst, docs/user-guide/kafka/kafka-connection-settings.rst, docs/user-guide/kafka/pydantic-schema-manager.rst, docs/user-guide/metrics/index.rst, safir/pyproject.toml, safir/src/safir/dependencies/metrics.py, safir/src/safir/kafka/_manager.py, safir/src/safir/metrics/__init__.py, safir/src/safir/metrics/_config.py, safir/src/safir/metrics/_constants.py, safir/src/safir/metrics/_event_manager.py, safir/src/safir/metrics/_exceptions.py, safir/src/safir/metrics/_models.py, safir/tests/conftest.py, safir/tests/event_manager_test.py
* An `EventManager` to register event schemas with a schema registry and provide a type-safe interface to publishing metrics events
* Config helpers for making an `EventManager` using the new Safir Kafka helpers
* A dependency to use in a Safir app
=> DM-45522: Metrics Events

safir/src/safir/kafka/_kafka_config.py, safir/src/safir/kafka/_schema_registry_config.py, safir/src/safir/metrics/_config.py
Allow Kafka and event metrics configuration to be loaded from YAML files generated from Helm value files, which use camel-case instead of Python's preferred snake-case. Unforunately, using an alias generator plus an environment variable prefix doesn't work the way that one would want, nor does using an environment variable prefix with fields that have aliases, so this requires explicitly listing the camel-case and environment variable aliases for fields that support both.
=> DM-46821: Allow camel-case for Kafka and events configuration

CHANGELOG.md, changelog.d/20240919_141153_danfuchs_kafka.md, changelog.d/20240924_161610_danfuchs_schema_manager.md, changelog.d/20241002_170409_danfuchs_metrics_events2.md, changelog.d/20241009_155401_danfuchs_vo_models_type_compatibility.md
Collect and edit the change log for the 6.5.0 release.
=> DM-46821: Prepare 6.5.0 release

CHANGELOG.md, changelog.d/20241021_091054_rra_DM_47011.md
Collect change log for 6.5.1 release.
=> DM-47011: Prepare 6.5.1 release

.pre-commit-config.yaml, docs/dev/release.rst, docs/user-guide/set-up-from-template.rst, noxfile.py, safir/tests/support/kafka/container.py
Bump pre-commit dependencies and fix a code pattern caught by the new version of Ruff.
=> DM-47011: Update pre-commit dependencies

docs/user-guide/database/schema.rst
Fix incorrect code highlighting, some missing code in the examples, and some missing details about the tox setup.
=> DM-47262: Fix Alembic documentation

docs/user-guide/database/pagination.rst, safir/src/safir/database/_pagination.py, safir/tests/database_test.py
Move the `COUNT` query for `PaginatedQueryRunner` to a separate `query_count` method so that the caller can choose not to perform a separate `COUNT` query and instead not return the total count information.
=> DM-47769: Do not do COUNT queries for pagination by default

CHANGELOG.md, changelog.d/20241112_163814_rra_DM_47262.md, changelog.d/20241113_152723_rra_DM_47262a.md, changelog.d/20241113_165421_rra_DM_47262b.md, changelog.d/20241119_132629_danfuchs_fix_metrics_timedelta.md, changelog.d/20241120_161839_danfuchs_event_manager_test_failures.md, changelog.d/20241122_150037_rra_DM_47769a.md, changelog.d/20241122_164744_danfuchs_metrics_publishing_is_slow.md, changelog.d/20241125_140320_rra_DM_47796.md, changelog.d/20241126_175555_steliosvoutsinas_DM_47459.md, ruff-shared.toml
Collect the change log for the 8.0.0 release and update the shared Ruff configuration file.
=> DM-47789: Prepare 8.0.0 release

docs/user-guide/database/pagination.rst
The example of how to set the response HTTP headers was using the old method of parsing the cursor and the wrong name for the query runner class. Fix both issues.
=> DM-47769: Fix pagination example

CHANGELOG.md
Create a change log for 9.1.0 since I forgot to use scriv for the changes in this release.
=> DM-48173: Prepare 9.1.0 release

CHANGELOG.md, changelog.d/20241218_162844_danfuchs_disable_kafka_x509_strict_verification.md
Collect the change log for the 9.1.1 release.
=> DM-48199: Prepare 9.1.1 release

safir/src/safir/database/_retry.py
The current version of mypy cannot handle a `ParamSpec` embedded in a `TypeAlias` and thinks it is not bound. Expand all the types rather than using a `TypeAlias`, which is ugly but works. We can simplify the code later once we can drop Python 3.11 support.
=> Remove TypeAlias in retry_async_transaction

.pre-commit-config.yaml, CHANGELOG.md, changelog.d/20250505_134035_rra_DM_50527.md
Collect change log for the 10.2.0 release and update pre-commit dependencies.
=> DM-50527: Prepare 10.2.0 release

.github/workflows/ci.yaml, .github/workflows/periodic-ci.yaml, .pre-commit-config.yaml, CHANGELOG.md, changelog.d/20250520_165506_rra_DM_50964.md, changelog.d/20250521_132914_rra_DM_50964.md, changelog.d/20250522_182327_rra_DM_50964a.md, changelog.d/20250527_121526_rra_DM_50964a.md, changelog.d/20250527_151125_rra_DM_50964a.md, safir/pyproject.toml
Collect change log for the 11.0.0 release. Update pre-commit dependencies.
=> DM-50964: Prepare 11.0.0 release

.pre-commit-config.yaml, CHANGELOG.md, changelog.d/20250821_164709_rra_DM_52238a.md
Collect the change log for the 12.0.1 release. Update pre-commit dependencies.
=> DM-52310: Prepare 12.0.1 release
